export const ROUTER_CHANGE_EVENT = 'monaReactRouterChange'
export const ROUTER_MISS_EVENT = 'monaReactRouterMiss'
export const ROUTER_CHANGE_FINISH_EVENT = 'monaReactRouterChangeFinish'
export const ROUTER_TYPE_KEY_HASH = 'hash'
export const ROUTER_TYPE_KEY_HISTORY = 'history'
